### ISSUE TITLE
Kogumiku detailvaade avab vaid meta

### ISSUE THREAD

**Issue by erkkijakobson** [e-koolikott/DOP#17]
Vajadus
- [x] lisada visuaalse regressiooni testid
- [x] peab olema sama detailvaade/mall mis materjali detailvaade
- [x] lingi või embeddi asemel on "ava esimene kogumiku peatükk"
